spring:
  application:
    name: mite
  datasource:
    url: jdbc:h2:tcp://localhost/~/jwbookdb
    username: jwbook
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/static/
server:
  port: 8080

openai:
  api:
    key: ysk-0ozGcf2Uav281BrD-cVMgysEedXLsTiSTpUDGfg3EQT3BlbkFJX-SF2CfThxgXxphkCJLs37SaMmoJvesXFJGAnxSaoA
    model: gpt-3.5-turbo
    url: https://api.openai.com/v1/chat/completions