spring:
  application:
    name: mite
  datasource:
    url: jdbc:h2:tcp://localhost/~/jwbookdb
    username: jwbook
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
server:
  port: 8080
